---
- name: Create temporary Ghost Secrets file
  ansible.builtin.copy:
    src: "../../kubernetes/ghost/ghost-secrets.yaml"
    dest: "/tmp/ghost-secrets.yaml"
    remote_src: no

- name: Replace database host placeholder with actual value (base64 encoded)
  ansible.builtin.replace:
    path: "/tmp/ghost-secrets.yaml"
    regexp: 'HOST_DB_GHOST'
    replace: "{{ terraform_outputs_json.rds_endpoint.value.split(':')[0] | b64encode }}"

- name: Replace database username placeholder with actual value (base64 encoded)
  ansible.builtin.replace:
    path: "/tmp/ghost-secrets.yaml"
    regexp: 'USERNAME_DB_GHOST'
    replace: "{{ terraform_outputs_json.rds_username.value | b64encode }}"

- name: Replace database password placeholder with actual value (base64 encoded)
  ansible.builtin.replace:
    path: "/tmp/ghost-secrets.yaml"
    regexp: 'PASSWORD_DB_GHOST'
    replace: "{{ terraform_outputs_json.rds_password.value | b64encode }}"

- name: Replace database name placeholder with actual value (base64 encoded)
  ansible.builtin.replace:
    path: "/tmp/ghost-secrets.yaml"
    regexp: 'DATABASE_NAME_GHOST'
    replace: "{{ terraform_outputs_json.rds_db_name.value | b64encode }}"

- name: Replace URL placeholder with actual value (base64 encoded)
  ansible.builtin.replace:
    path: "/tmp/ghost-secrets.yaml"
    regexp: 'URL_GHOST'
    replace: "{{ terraform_outputs_json.url_ghost.value | b64encode }}"

- name: Upload the modified Ghost Secrets file to S3
  ansible.builtin.command:
    cmd: aws s3 cp /tmp/ghost-secrets.yaml s3://{{ terraform_outputs_json.bucket_name.value }}/ghost-secrets.yaml

