---
- name: Update kubeconfig to connect to EKS cluster
  ansible.builtin.command:
    cmd: aws eks update-kubeconfig --region "{{ aws_region_output.stdout }}" --name "{{ eks_cluster_name_output.stdout }}"

